name: MixAnyEnchant
version: 1.0.0
api-version: 1.13
description: A plugin that would allow players to add any enchantement to any item, and regardless of what other enchantements are already on it.
main: main.Loader